'use strict'

import { expect } from 'chai'
import toLowerCase from './to-lower-case'

it('Should toLowerCase to be a function', () => {
  expect(toLowerCase).to.be.a('function')
})

it('Should toLowerCase convert vowels', () => {
  expect(toLowerCase('A')).to.be.equal('a')
  expect(toLowerCase('E')).to.be.equal('e')
  expect(toLowerCase('I')).to.be.equal('i')
  expect(toLowerCase('O')).to.be.equal('o')
  expect(toLowerCase('U')).to.be.equal('u')
})

it('Should toLowerCase convert consonants', () => {
  expect(toLowerCase('A')).to.be.equal('a')
  expect(toLowerCase('B')).to.be.equal('b')
  expect(toLowerCase('C')).to.be.equal('c')
  expect(toLowerCase('D')).to.be.equal('d')
  expect(toLowerCase('E')).to.be.equal('e')
  expect(toLowerCase('F')).to.be.equal('f')
  expect(toLowerCase('G')).to.be.equal('g')
  expect(toLowerCase('H')).to.be.equal('h')
  expect(toLowerCase('I')).to.be.equal('i')
  expect(toLowerCase('J')).to.be.equal('j')
  expect(toLowerCase('K')).to.be.equal('k')
  expect(toLowerCase('L')).to.be.equal('l')
  expect(toLowerCase('M')).to.be.equal('m')
  expect(toLowerCase('N')).to.be.equal('n')
  expect(toLowerCase('O')).to.be.equal('o')
  expect(toLowerCase('P')).to.be.equal('p')
  expect(toLowerCase('Q')).to.be.equal('q')
  expect(toLowerCase('R')).to.be.equal('r')
  expect(toLowerCase('S')).to.be.equal('s')
  expect(toLowerCase('T')).to.be.equal('t')
  expect(toLowerCase('U')).to.be.equal('u')
  expect(toLowerCase('V')).to.be.equal('v')
  expect(toLowerCase('W')).to.be.equal('w')
  expect(toLowerCase('X')).to.be.equal('x')
  expect(toLowerCase('Y')).to.be.equal('y')
  expect(toLowerCase('Z')).to.be.equal('z')
})

it('Should convert more than one character', () => {
  expect(toLowerCase('STR')).to.be.equal('str')
  expect(toLowerCase('StR')).to.be.equal('str')
  expect(toLowerCase('sTR')).to.be.equal('str')
  expect(toLowerCase('TEST')).to.be.equal('test')
  expect(toLowerCase('John was born in New York')).to.be.equal('john was born in new york')
  expect(toLowerCase('The ocean is saltwater')).to.be.equal('the ocean is saltwater')
})

it('Should convert unicode table characters', () => {
  expect(toLowerCase('À')).to.be.equal('à')
  expect(toLowerCase('Á')).to.be.equal('á')
  expect(toLowerCase('Â')).to.be.equal('â')
  expect(toLowerCase('Ã')).to.be.equal('ã')
  expect(toLowerCase('Ä')).to.be.equal('ä')
  expect(toLowerCase('Å')).to.be.equal('å')
  expect(toLowerCase('Æ')).to.be.equal('æ')
  expect(toLowerCase('Ç')).to.be.equal('ç')
  expect(toLowerCase('È')).to.be.equal('è')
  expect(toLowerCase('É')).to.be.equal('é')
  expect(toLowerCase('Ê')).to.be.equal('ê')
  expect(toLowerCase('Ë')).to.be.equal('ë')
  expect(toLowerCase('Ì')).to.be.equal('ì')
  expect(toLowerCase('Í')).to.be.equal('í')
  expect(toLowerCase('Î')).to.be.equal('î')
  expect(toLowerCase('Ï')).to.be.equal('ï')
  expect(toLowerCase('Ð')).to.be.equal('ð')
  expect(toLowerCase('Ñ')).to.be.equal('ñ')
  expect(toLowerCase('Ò')).to.be.equal('ò')
  expect(toLowerCase('Ó')).to.be.equal('ó')
  expect(toLowerCase('Ô')).to.be.equal('ô')
  expect(toLowerCase('Õ')).to.be.equal('õ')
  expect(toLowerCase('Ö')).to.be.equal('ö')
  expect(toLowerCase('Ø')).to.be.equal('ø')
  expect(toLowerCase('Ù')).to.be.equal('ù')
  expect(toLowerCase('Ú')).to.be.equal('ú')
  expect(toLowerCase('Û')).to.be.equal('û')
  expect(toLowerCase('Ü')).to.be.equal('ü')
  expect(toLowerCase('Ý')).to.be.equal('ý')
  expect(toLowerCase('Þ')).to.be.equal('þ')
})
